#include<stdio.h>
void main()
{
     int n1,n2,n3;
     printf("enter three number:");
     scanf("%d_%d_%d",&n1,&n2,&n3);  
     if(n1>n2&&n1>n3)
     printf("%d is the largest number",n1);
     else if(n2>n1&& n2>n3)
     printf("%d is the largest number ", n2);
     else if(n3>n1&& n3>n2)
     printf("%d is the largest number ", n3);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
}